// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SHOP.CO.Infrastructure.Persistence;

#nullable disable

namespace SHOP.CO.Infrastructure.Migrations
{
    [DbContext(typeof(ShopCoDbContext))]
    partial class ShopCoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SHOP.CO.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SelectedSize")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_CartItems_SessionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CartItems_UserId");

                    b.HasIndex("VariantId");

                    b.ToTable("CartItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CartItems_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_CartItems_UserOrSession", "[UserId] IS NOT NULL OR [SessionId] IS NOT NULL");
                        });

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSelected = true,
                            Quantity = 2,
                            SelectedColor = "Trắng",
                            SelectedSize = "M",
                            UnitPrice = 120000m,
                            UserId = 2,
                            VariantId = 1
                        },
                        new
                        {
                            CartItemId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSelected = true,
                            Quantity = 1,
                            SelectedColor = "Xanh Denim",
                            SelectedSize = "30",
                            UnitPrice = 399000m,
                            UserId = 2,
                            VariantId = 5
                        },
                        new
                        {
                            CartItemId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSelected = false,
                            Quantity = 1,
                            SelectedColor = "Trắng",
                            SelectedSize = "M",
                            UnitPrice = 250000m,
                            UserId = 3,
                            VariantId = 7
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categories_Slug");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Thời trang Nam",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Slug = "thoi-trang-nam",
                            SortOrder = 0
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Thời trang Nữ",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Slug = "thoi-trang-nu",
                            SortOrder = 0
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Unisex",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Slug = "thoi-trang-unisex",
                            SortOrder = 0
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Áo Thun Nam",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParentCategoryId = 1,
                            Slug = "ao-thun-nam",
                            SortOrder = 0
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Quần Jeans Nam",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParentCategoryId = 1,
                            Slug = "quan-jeans-nam",
                            SortOrder = 0
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Váy Nữ",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParentCategoryId = 2,
                            Slug = "vay-nu",
                            SortOrder = 0
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Áo Sơ Mi Nữ",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ParentCategoryId = 2,
                            Slug = "ao-so-mi-nu",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.CommerceRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("DiscountType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("RecordId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("VariantId");

                    b.HasIndex("RecordType", "Status")
                        .HasDatabaseName("IX_CommerceRecords_Type_Status");

                    b.ToTable("CommerceRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_CommerceRecords_DiscountType", "[DiscountType] IS NULL OR [DiscountType] IN (N'Percent', N'Fixed')");

                            t.HasCheckConstraint("CK_CommerceRecords_PayloadJson", "[PayloadJson] IS NULL OR ISJSON([PayloadJson]) = 1");

                            t.HasCheckConstraint("CK_CommerceRecords_PaymentMethod", "[PaymentMethod] IS NULL OR [PaymentMethod] IN (N'COD', N'Online')");

                            t.HasCheckConstraint("CK_CommerceRecords_Type", "[RecordType] IN (N'Payment', N'Voucher', N'VoucherUsage', N'FlashSale', N'HotDeal')");
                        });

                    b.HasData(
                        new
                        {
                            RecordId = 1,
                            Amount = 240000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 1,
                            PaymentMethod = "Online",
                            PaymentProvider = "VNPay",
                            RecordType = "Payment",
                            Status = "Success",
                            TransactionCode = "VNP123456",
                            UsedCount = 0,
                            UserId = 2
                        },
                        new
                        {
                            RecordId = 2,
                            Code = "FREESHIP19K",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountType = "Fixed",
                            DiscountValue = 19000m,
                            OrderId = 2,
                            RecordType = "VoucherUsage",
                            Status = "Applied",
                            UsedCount = 0,
                            UserId = 2
                        },
                        new
                        {
                            RecordId = 3,
                            Amount = 300000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 3,
                            PaymentMethod = "COD",
                            RecordType = "Payment",
                            Status = "Pending",
                            UsedCount = 0,
                            UserId = 3
                        },
                        new
                        {
                            RecordId = 4,
                            Code = "WELCOME50",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountType = "Fixed",
                            DiscountValue = 50000m,
                            EndAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinOrderAmount = 200000m,
                            Name = "Giảm 50K cho thành viên mới",
                            RecordType = "Voucher",
                            StartAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UsageLimit = 1000,
                            UsedCount = 150
                        },
                        new
                        {
                            RecordId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sale 11.11",
                            PayloadJson = "{\"discountPercent\": 10}",
                            RecordType = "FlashSale",
                            StartAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UsedCount = 0
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.CustomerActivity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("InputJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Keyword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("ActivityId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.HasIndex("UserId", "ActivityType")
                        .HasDatabaseName("IX_CustomerActivities_User_Type");

                    b.ToTable("CustomerActivities", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomerActivities_InputJson", "[InputJson] IS NULL OR ISJSON([InputJson]) = 1");

                            t.HasCheckConstraint("CK_CustomerActivities_Rating", "[Rating] IS NULL OR ([Rating] >= 1 AND [Rating] <= 5)");

                            t.HasCheckConstraint("CK_CustomerActivities_ResultJson", "[ResultJson] IS NULL OR ISJSON([ResultJson]) = 1");

                            t.HasCheckConstraint("CK_CustomerActivities_Type", "[ActivityType] IN (N'Wishlist', N'Review', N'RecentlyViewed', N'Search', N'AiSize', N'AiOutfit', N'AiColorSearch')");
                        });

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            ActivityType = "Review",
                            Comment = "Áo chất lượng rất tốt, form chuẩn.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OrderItemId = 1,
                            ProductId = 1,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            ActivityId = 2,
                            ActivityType = "Wishlist",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductId = 5,
                            UserId = 3
                        },
                        new
                        {
                            ActivityId = 3,
                            ActivityType = "Search",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "quần jeans nam",
                            UserId = 2
                        },
                        new
                        {
                            ActivityId = 4,
                            ActivityType = "RecentlyViewed",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductId = 2,
                            UserId = 3
                        },
                        new
                        {
                            ActivityId = 5,
                            ActivityType = "AiColorSearch",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InputJson = "{\"imageUrl\": \"/uploads/user-search-1.jpg\"}",
                            IsActive = true,
                            ResultJson = "{\"dominantColor\": \"#FF0000\", \"matchScore\": 95}",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.InteractionLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("EntitiesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityChanged")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenderType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.HasIndex("UserId", "LogType")
                        .HasDatabaseName("IX_InteractionLogs_User_Type");

                    b.ToTable("InteractionLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_InteractionLogs_EntitiesJson", "[EntitiesJson] IS NULL OR ISJSON([EntitiesJson]) = 1");

                            t.HasCheckConstraint("CK_InteractionLogs_NewValueJson", "[NewValueJson] IS NULL OR ISJSON([NewValueJson]) = 1");

                            t.HasCheckConstraint("CK_InteractionLogs_OldValueJson", "[OldValueJson] IS NULL OR ISJSON([OldValueJson]) = 1");

                            t.HasCheckConstraint("CK_InteractionLogs_PayloadJson", "[PayloadJson] IS NULL OR ISJSON([PayloadJson]) = 1");

                            t.HasCheckConstraint("CK_InteractionLogs_SenderType", "[SenderType] IS NULL OR [SenderType] IN (N'User', N'Bot', N'System', N'Admin')");

                            t.HasCheckConstraint("CK_InteractionLogs_Type", "[LogType] IN (N'Chatbot', N'Notification', N'Email', N'Audit', N'StockMovement', N'StockAlert', N'ReportExport')");
                        });

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            LogType = "Chatbot",
                            Message = "Cho tôi hỏi quần jeans size 30 còn hàng không?",
                            SenderType = "User",
                            SessionId = "sess_123",
                            UserId = 2
                        },
                        new
                        {
                            LogId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntitiesJson = "{\"product\": \"quần jeans\", \"size\": \"30\"}",
                            IntentName = "check_stock",
                            IsRead = true,
                            LogType = "Chatbot",
                            Message = "Dạ, quần jeans nam slimfit size 30 hiện còn 40 sản phẩm ạ.",
                            SenderType = "Bot",
                            SessionId = "sess_123",
                            UserId = 2
                        },
                        new
                        {
                            LogId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            LogType = "Notification",
                            Message = "Đơn hàng ORD-0003 của bạn đã được giao cho đơn vị vận chuyển.",
                            OrderId = 3,
                            Status = "Sent",
                            Title = "Đơn hàng đang giao",
                            UserId = 3
                        },
                        new
                        {
                            LogId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            LogType = "StockAlert",
                            Message = "Biến thể QJN-XANH-31 chỉ còn 3 sản phẩm trong kho.",
                            ProductId = 4,
                            SenderType = "System",
                            Title = "Cảnh báo tồn kho thấp",
                            UserId = 1,
                            VariantId = 6
                        },
                        new
                        {
                            LogId = 5,
                            ActionName = "UpdateProductPrice",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            LogType = "Audit",
                            NewValueJson = "{\"price\": 399000}",
                            OldValueJson = "{\"price\": 400000}",
                            SenderType = "Admin",
                            Title = "Cập nhật giá sản phẩm",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unpaid");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddressText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ShippingFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ShippingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("NotShipped");

                    b.Property<string>("StaffNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SubtotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Orders_OrderCode");

                    b.HasIndex("OrderStatus")
                        .HasDatabaseName("IX_Orders_OrderStatus");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Orders_UserId");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_OrderStatus", "[OrderStatus] IN (N'Pending', N'Confirmed', N'Shipping', N'Completed', N'Canceled')");

                            t.HasCheckConstraint("CK_Orders_PaymentStatus", "[PaymentStatus] IN (N'Unpaid', N'Paid', N'Failed', N'Refunded')");

                            t.HasCheckConstraint("CK_Orders_TotalAmount", "[TotalAmount] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            AddressId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 0m,
                            OrderCode = "ORD-0001",
                            OrderStatus = "Completed",
                            PaymentStatus = "Paid",
                            ReceiverName = "Nguyễn Văn A",
                            ReceiverPhone = "0901234567",
                            ShippingAddressText = "123 Lê Lợi, Quận 1, TP.HCM",
                            ShippingFee = 0m,
                            ShippingStatus = "Completed",
                            SubtotalAmount = 240000m,
                            TotalAmount = 240000m,
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 2,
                            AddressId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 19000m,
                            OrderCode = "ORD-0002",
                            OrderStatus = "Pending",
                            PaymentStatus = "Unpaid",
                            ReceiverName = "Nguyễn Văn A (Công ty)",
                            ReceiverPhone = "0901234567",
                            ShippingAddressText = "456 Nguyễn Huệ, Quận 1, TP.HCM",
                            ShippingFee = 0m,
                            ShippingStatus = "NotShipped",
                            SubtotalAmount = 399000m,
                            TotalAmount = 380000m,
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 3,
                            AddressId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 0m,
                            OrderCode = "ORD-0003",
                            OrderStatus = "Shipping",
                            PaymentStatus = "Paid",
                            ReceiverName = "Trần Thị B",
                            ReceiverPhone = "0987654321",
                            ShippingAddressText = "789 Hai Bà Trưng, Quận 3, TP.HCM",
                            ShippingFee = 0m,
                            ShippingStatus = "Shipping",
                            SubtotalAmount = 300000m,
                            TotalAmount = 300000m,
                            UserId = 3
                        },
                        new
                        {
                            OrderId = 4,
                            AddressId = 3,
                            CancelReason = "Đổi ý",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 0m,
                            OrderCode = "ORD-0004",
                            OrderStatus = "Canceled",
                            PaymentStatus = "Refunded",
                            ReceiverName = "Trần Thị B",
                            ReceiverPhone = "0987654321",
                            ShippingAddressText = "789 Hai Bà Trưng, Quận 3, TP.HCM",
                            ShippingFee = 0m,
                            ShippingStatus = "NotShipped",
                            SubtotalAmount = 400000m,
                            TotalAmount = 400000m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<string>("ColorSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ImageUrlSnapshot")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("NotReviewed");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SizeSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SkuSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItems_OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_LineTotal", "[LineTotal] >= 0");

                            t.HasCheckConstraint("CK_OrderItems_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_OrderItems_ReviewStatus", "[ReviewStatus] IN (N'NotReviewed', N'Reviewed')");
                        });

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            ColorSnapshot = "Trắng",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 0m,
                            ImageUrlSnapshot = "/images/dressstyleimg1.png",
                            LineTotal = 240000m,
                            OrderId = 1,
                            ProductId = 1,
                            ProductNameSnapshot = "Áo Thun Cổ Tròn Basic",
                            Quantity = 2,
                            ReviewStatus = "Reviewed",
                            SalePrice = 120000m,
                            SizeSnapshot = "M",
                            SkuSnapshot = "ATB-TR-M",
                            UnitPrice = 150000m,
                            VariantId = 1
                        },
                        new
                        {
                            OrderItemId = 2,
                            ColorSnapshot = "Xanh Denim",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 0m,
                            ImageUrlSnapshot = "/images/newarrivalimg2.png",
                            LineTotal = 399000m,
                            OrderId = 2,
                            ProductId = 4,
                            ProductNameSnapshot = "Quần Jeans Nam Slimfit",
                            Quantity = 1,
                            ReviewStatus = "NotReviewed",
                            SalePrice = 399000m,
                            SizeSnapshot = "30",
                            SkuSnapshot = "QJN-XANH-30",
                            UnitPrice = 450000m,
                            VariantId = 5
                        },
                        new
                        {
                            OrderItemId = 3,
                            ColorSnapshot = "Đỏ",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 0m,
                            ImageUrlSnapshot = "/images/dressstyleimg3.png",
                            LineTotal = 300000m,
                            OrderId = 3,
                            ProductId = 2,
                            ProductNameSnapshot = "Váy Hoa Mùa Hè",
                            Quantity = 1,
                            ReviewStatus = "NotReviewed",
                            SalePrice = 300000m,
                            SizeSnapshot = "S",
                            SkuSnapshot = "VHM-DO-S",
                            UnitPrice = 350000m,
                            VariantId = 3
                        },
                        new
                        {
                            OrderItemId = 4,
                            ColorSnapshot = "Xám",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 0m,
                            ImageUrlSnapshot = "/images/heroimg.png",
                            LineTotal = 400000m,
                            OrderId = 4,
                            ProductId = 3,
                            ProductNameSnapshot = "Áo Khoác Hoodie Unisex",
                            Quantity = 1,
                            ReviewStatus = "NotReviewed",
                            SalePrice = 400000m,
                            SizeSnapshot = "XL",
                            SkuSnapshot = "AKH-XA-XL",
                            UnitPrice = 400000m,
                            VariantId = 4
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderTarget")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBestSeller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsNewArrival")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Products_CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_Products_Slug");

                    b.HasIndex("IsActive", "IsFeatured", "IsBestSeller", "IsNewArrival")
                        .HasDatabaseName("IX_Products_SearchFlags");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_BasePrice", "[BasePrice] >= 0");

                            t.HasCheckConstraint("CK_Products_Rating", "[AverageRating] >= 0 AND [AverageRating] <= 5");

                            t.HasCheckConstraint("CK_Products_SalePrice", "[SalePrice] IS NULL OR [SalePrice] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AverageRating = 4.5m,
                            BasePrice = 150000m,
                            Brand = "Shop.Co",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsBestSeller = true,
                            IsFeatured = false,
                            IsNewArrival = false,
                            Material = "Cotton",
                            ProductName = "Áo Thun Cổ Tròn Basic",
                            ReviewCount = 10,
                            SalePrice = 120000m,
                            Slug = "ao-thun-co-tron-basic",
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 2,
                            AverageRating = 4.8m,
                            BasePrice = 350000m,
                            Brand = "Shop.Co",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsBestSeller = false,
                            IsFeatured = false,
                            IsNewArrival = true,
                            Material = "Voan",
                            ProductName = "Váy Hoa Mùa Hè",
                            ReviewCount = 25,
                            SalePrice = 300000m,
                            Slug = "vay-hoa-mua-he",
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 3,
                            AverageRating = 4.2m,
                            BasePrice = 400000m,
                            Brand = "Shop.Co",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNewArrival = false,
                            Material = "Nỉ",
                            ProductName = "Áo Khoác Hoodie Unisex",
                            ReviewCount = 5,
                            SalePrice = 400000m,
                            Slug = "ao-khoac-hoodie-unisex",
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 4,
                            AverageRating = 4.9m,
                            BasePrice = 450000m,
                            Brand = "DenimX",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsBestSeller = true,
                            IsFeatured = false,
                            IsNewArrival = false,
                            Material = "Denim",
                            ProductName = "Quần Jeans Nam Slimfit",
                            ReviewCount = 50,
                            SalePrice = 399000m,
                            Slug = "quan-jeans-nam-slimfit",
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 5,
                            AverageRating = 4.0m,
                            BasePrice = 250000m,
                            Brand = "OfficeWear",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsBestSeller = false,
                            IsFeatured = false,
                            IsNewArrival = false,
                            Material = "Lụa",
                            ProductName = "Áo Sơ Mi Lụa Công Sở",
                            ReviewCount = 2,
                            Slug = "ao-so-mi-lua-cong-so",
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ColorAnalysisJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("DominantColorHex")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsThumbnail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ProductImages_ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("ProductImages", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductImages_ColorAnalysisJson", "[ColorAnalysisJson] IS NULL OR ISJSON([ColorAnalysisJson]) = 1");
                        });

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/dressstyleimg1.png",
                            IsThumbnail = true,
                            ProductId = 1,
                            SortOrder = 1,
                            VariantId = 1
                        },
                        new
                        {
                            ImageId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/newarrivalimg1.png",
                            IsThumbnail = false,
                            ProductId = 1,
                            SortOrder = 2,
                            VariantId = 2
                        },
                        new
                        {
                            ImageId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/dressstyleimg3.png",
                            IsThumbnail = true,
                            ProductId = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            ImageId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/heroimg.png",
                            IsThumbnail = true,
                            ProductId = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            ImageId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/newarrivalimg2.png",
                            IsThumbnail = true,
                            ProductId = 4,
                            SortOrder = 1,
                            VariantId = 5
                        },
                        new
                        {
                            ImageId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/topsellingimg4.png",
                            IsThumbnail = false,
                            ProductId = 4,
                            SortOrder = 2,
                            VariantId = 6
                        },
                        new
                        {
                            ImageId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/topsellingimg1.png",
                            IsThumbnail = true,
                            ProductId = 5,
                            SortOrder = 1
                        },
                        new
                        {
                            ImageId = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://via.placeholder.com/600x800.png?text=Ao+Thun+Trang",
                            IsThumbnail = true,
                            ProductId = 1,
                            SortOrder = 1,
                            VariantId = 1
                        },
                        new
                        {
                            ImageId = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://via.placeholder.com/600x800.png?text=Ao+Thun+Den",
                            IsThumbnail = false,
                            ProductId = 1,
                            SortOrder = 2,
                            VariantId = 2
                        },
                        new
                        {
                            ImageId = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://via.placeholder.com/600x800.png?text=Vay+Hoa",
                            IsThumbnail = true,
                            ProductId = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            ImageId = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://via.placeholder.com/600x800.png?text=Hoodie+Xam",
                            IsThumbnail = true,
                            ProductId = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            ImageId = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://via.placeholder.com/600x800.png?text=Jeans+Denim",
                            IsThumbnail = true,
                            ProductId = 4,
                            SortOrder = 1,
                            VariantId = 5
                        },
                        new
                        {
                            ImageId = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://via.placeholder.com/600x800.png?text=Jeans+Dam",
                            IsThumbnail = false,
                            ProductId = 4,
                            SortOrder = 2,
                            VariantId = 6
                        },
                        new
                        {
                            ImageId = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://via.placeholder.com/600x800.png?text=So+Mi+Trang",
                            IsThumbnail = true,
                            ProductId = 5,
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantId"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<decimal>("ExtraPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LowStockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WeightGram")
                        .HasColumnType("int");

                    b.HasKey("VariantId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_ProductVariants_ProductId");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UQ_ProductVariants_Sku");

                    b.ToTable("ProductVariants", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductVariants_LowStock", "[LowStockThreshold] >= 0");

                            t.HasCheckConstraint("CK_ProductVariants_Stock", "[StockQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            VariantId = 1,
                            Color = "Trắng",
                            ColorHex = "#FFFFFF",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 0m,
                            IsActive = true,
                            LowStockThreshold = 5,
                            ProductId = 1,
                            Size = "M",
                            Sku = "ATB-TR-M",
                            StockQuantity = 50
                        },
                        new
                        {
                            VariantId = 2,
                            Color = "Đen",
                            ColorHex = "#000000",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 0m,
                            IsActive = true,
                            LowStockThreshold = 5,
                            ProductId = 1,
                            Size = "L",
                            Sku = "ATB-DE-L",
                            StockQuantity = 30
                        },
                        new
                        {
                            VariantId = 3,
                            Color = "Đỏ",
                            ColorHex = "#FF0000",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 0m,
                            IsActive = true,
                            LowStockThreshold = 2,
                            ProductId = 2,
                            Size = "S",
                            Sku = "VHM-DO-S",
                            StockQuantity = 20
                        },
                        new
                        {
                            VariantId = 4,
                            Color = "Xám",
                            ColorHex = "#808080",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 0m,
                            IsActive = true,
                            LowStockThreshold = 10,
                            ProductId = 3,
                            Size = "XL",
                            Sku = "AKH-XA-XL",
                            StockQuantity = 100
                        },
                        new
                        {
                            VariantId = 5,
                            Color = "Xanh Denim",
                            ColorHex = "#1560BD",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 0m,
                            IsActive = true,
                            LowStockThreshold = 5,
                            ProductId = 4,
                            Size = "30",
                            Sku = "QJN-XANH-30",
                            StockQuantity = 40
                        },
                        new
                        {
                            VariantId = 6,
                            Color = "Xanh Đậm",
                            ColorHex = "#00008B",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 0m,
                            IsActive = true,
                            LowStockThreshold = 5,
                            ProductId = 4,
                            Size = "31",
                            Sku = "QJN-XANH-31",
                            StockQuantity = 3
                        },
                        new
                        {
                            VariantId = 7,
                            Color = "Trắng",
                            ColorHex = "#FFFFFF",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraPrice = 0m,
                            IsActive = true,
                            LowStockThreshold = 5,
                            ProductId = 5,
                            Size = "M",
                            Sku = "ASM-TR-M",
                            StockQuantity = 15
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsNewsletterSubscribed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredSize")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredStyle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResetPasswordExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Customer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerificationExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN (N'Customer', N'Staff', N'Admin')");

                            t.HasCheckConstraint("CK_Users_Status", "[Status] IN (N'Unverified', N'Active', N'Locked', N'Deleted')");
                        });

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@shop.co",
                            FullName = "Admin System",
                            IsNewsletterSubscribed = false,
                            PasswordHash = "hashed123",
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenvana@gmail.com",
                            FullName = "Nguyễn Văn A",
                            Gender = "Nam",
                            IsNewsletterSubscribed = false,
                            PasswordHash = "hashed123",
                            Role = "Customer",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranthib@gmail.com",
                            FullName = "Trần Thị B",
                            Gender = "Nữ",
                            IsNewsletterSubscribed = false,
                            PasswordHash = "hashed123",
                            Role = "Customer",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.UserAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserAddresses_UserId");

                    b.ToTable("UserAddresses", (string)null);

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Quận 1",
                            IsDefault = true,
                            Province = "TP.HCM",
                            ReceiverName = "Nguyễn Văn A",
                            ReceiverPhone = "0901234567",
                            StreetAddress = "123 Lê Lợi",
                            UserId = 2,
                            Ward = "Phường Bến Nghé"
                        },
                        new
                        {
                            AddressId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Quận 1",
                            IsDefault = false,
                            Province = "TP.HCM",
                            ReceiverName = "Nguyễn Văn A (Công ty)",
                            ReceiverPhone = "0901234567",
                            StreetAddress = "456 Nguyễn Huệ",
                            UserId = 2,
                            Ward = "Phường Bến Nghé"
                        },
                        new
                        {
                            AddressId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Quận 3",
                            IsDefault = true,
                            Province = "TP.HCM",
                            ReceiverName = "Trần Thị B",
                            ReceiverPhone = "0987654321",
                            StreetAddress = "789 Hai Bà Trưng",
                            UserId = 3,
                            Ward = "Phường 6"
                        });
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SHOP.CO.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.Category", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.CommerceRecord", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.Order", "Order")
                        .WithMany("CommerceRecords")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SHOP.CO.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SHOP.CO.Domain.Entities.User", "User")
                        .WithMany("CommerceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SHOP.CO.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.CustomerActivity", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SHOP.CO.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SHOP.CO.Domain.Entities.User", "User")
                        .WithMany("CustomerActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SHOP.CO.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrderItem");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.InteractionLog", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SHOP.CO.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SHOP.CO.Domain.Entities.User", "User")
                        .WithMany("InteractionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SHOP.CO.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.Order", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.UserAddress", "UserAddress")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SHOP.CO.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SHOP.CO.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SHOP.CO.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.Product", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SHOP.CO.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("SHOP.CO.Domain.Entities.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.Order", b =>
                {
                    b.Navigation("CommerceRecords");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.ProductVariant", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SHOP.CO.Domain.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("CommerceRecords");

                    b.Navigation("CustomerActivities");

                    b.Navigation("InteractionLogs");

                    b.Navigation("Orders");

                    b.Navigation("UserAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
